version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my-market-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vladimir
      POSTGRES_PASSWORD: vladimir
      POSTGRES_DB: mymarket
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
